### ISSUE TITLE
Test discrepancy 

### ISSUE THREAD

**Issue by HarlemSquirrel** [jspillers/sema_api_ruby#2]
I noticed when testing with my own API key and deleting the cassettes the following expects `0.0` but I actually got `0.0025`. This image does have some text so that seems to make sense. 

```ruby
# spec/lib/sema_api_ruby/client/ocr_spec.rb
it 'returns the correct ratio for a png' do
  expect(api_client.text_to_image_ratio(test_png_image_path)).to eq 0.0
end 
```

**Comment by jspillers** [comment]
Yeah, this is pretty normal... their API will even return slightly different values for the same image when doing the same request day to day. I am assuming it is constantly shifting due to them adding new training data to their learning algo.

**Comment by HarlemSquirrel** [comment]
Ah, makes sense!
